[package]
name = "sentinel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
url = "2.3.1"
config = "0.13.2"
toml = "0.5.9"
deref-derive = "0.1.0"
clap = { version = "4.0.26", features = ["derive", "cargo"] }
error-stack = "0.2.4"
serde_json = "1.0.89"
tracing = { version = "0.1.37", features = ["valuable", "log"] }
tracing-subscriber = { version = "0.3.16", features = ["json", "valuable"] }
valuable = { version = "0.1.0", features = ["derive"] }
tracing-core = { version = "0.1.30", features = ["valuable"] }
